### ISSUE TITLE
src de imagem errados

### ISSUE THREAD

**Issue by aldairandre** [Arturgouveia1970/landing_page#1]
Estive a dar uma olhada para teu código, o caminho presente no teu site é absoluto,se ainda tiveres as imagens do projeto, aconselho te a muda as imagens para uma pasta img dentro do directorio do teu projeto e  mudar o caminho do src para um caminho relativo.
Alem disso tbm notei que não fizeste uma versao mobile do site, aconselho te a remover este app do teu dos teus projeto principais porque isso da uma péssima imagem para o recrutadores.

**Comment by Arturgouveia1970** [comment]
Boa noite Aldair, tens razao, isso foi um projecto experimental ao qual não dei a devida atenção. Vou tira-lo dos meus projectos.
Obrigado pelo feedback
